######################################################################
#
# File name : aurora_64b66b_0_TB_simulate.do
# Created on: Fri Aug 10 15:26:27 +07 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L axis_infrastructure_v1_1_0 -L axis_register_slice_v1_1_16 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.aurora_64b66b_0_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {aurora_64b66b_0_TB_wave.do}

view wave
view structure
view signals

do {aurora_64b66b_0_TB.udo}

run 1000ns
