######################################################################
#
# File name : aurora_64b66b_0_TB.udo
# Created on: Fri Aug 10 13:26:18 +07 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
