webtalk_init -webtalk_dir /home/callie/Desktop/xilinxauroratest/aurora_64b66b_0_ex/aurora_64b66b_0_ex.sim/sim_1/behav/xsim/xsim.dir/aurora_64b66b_0_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Aug 10 13:26:16 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174122087_174122088_210681506_668" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b1644c3d-e6a2-4bdc-a28a-8131503bb3af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ef503a0e69464df6abe7b79e4e7c1262" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2867.547 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "69248264 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "228.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "424928_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3672286623 -regid "174122087_174122088_210681506_668" -xml /home/callie/Desktop/xilinxauroratest/aurora_64b66b_0_ex/aurora_64b66b_0_ex.sim/sim_1/behav/xsim/xsim.dir/aurora_64b66b_0_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/callie/Desktop/xilinxauroratest/aurora_64b66b_0_ex/aurora_64b66b_0_ex.sim/sim_1/behav/xsim/xsim.dir/aurora_64b66b_0_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/callie/Desktop/xilinxauroratest/aurora_64b66b_0_ex/aurora_64b66b_0_ex.sim/sim_1/behav/xsim/xsim.dir/aurora_64b66b_0_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
