# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci
# IP: The module: 'aurora_64b66b_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci
# IP: The module: 'aurora_64b66b_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/callie/Desktop/xilinxauroratest/project_1/project_1.srcs/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'aurora_64b66b_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
